### ISSUE TITLE
there is no reactor running, must be called from the context of Tokio runtime

### ISSUE THREAD

**Issue by gangliao** [awslabs/aws-lambda-rust-runtime#266]
```rust
use lambda::{handler_fn, Context};
use serde_json::Value;

type Error = Box<dyn std::error::Error + Sync + Send + 'static>;

#[tokio::main]
async fn main() -> Result<(), Error> {
    lambda::run(handler_fn(handler)).await?;
    Ok(())
}

async fn handler(event: Value, _: Context) -> Result<Value, Error> {
    Ok(event)
}

#[cfg(test)]
mod tests {
    use super::*;
    use serde_json::json;

    #[tokio::test]
    async fn handler_handles() {
        let event = json!({
            "answer": 42
        });
        assert_eq!(
            handler(event.clone(), Context::default())
                .await
                .expect("expected Ok(_) value"),
            event
        )
    }
}
```
Hi @softprops @leepa @bdonlan @endor @marcbowes ,

When I run the code you provided above in the Lambda function, I got the following error.  How can I fix it?

```bash
START RequestId: 067ed0e7-d441-4ed2-a77c-38f9b90bc0b5 Version: $LATEST
thread 'main' panicked at 'there is no reactor running, must be called from the context of Tokio runtime', /home/gangliao/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.22/src/io/driver/mod.rs:202:14
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
END RequestId: 067ed0e7-d441-4ed2-a77c-38f9b90bc0b5
REPORT RequestId: 067ed0e7-d441-4ed2-a77c-38f9b90bc0b5	Duration: 193.80 ms	Billed Duration: 200 ms	Memory Size: 128 MB	Max Memory Used: 6 MB	
RequestId: 067ed0e7-d441-4ed2-a77c-38f9b90bc0b5 Error: Runtime exited with error: exit status 101
Runtime.ExitError
```

**Comment by gangliao** [comment]
more output

```bash
db9ec823/async-stream-0.2.1/src/async_stream.rs:53:17
  63: <core::pin::Pin<P> as futures_core::stream::Stream>::poll_next
             at /home/gangliao/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-core-0.3.7/src/stream.rs:129:9
  64: futures_util::stream::stream::StreamExt::poll_next_unpin
             at /home/gangliao/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.7/src/stream/stream/mod.rs:1330:9
  65: <futures_util::stream::stream::next::Next<St> as core::future::future::Future>::poll
             at /home/gangliao/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.7/src/stream/stream/next.rs:35:9
  66: lambda::run_inner::{{closure}}
             at /home/gangliao/.cargo/git/checkouts/aws-lambda-rust-runtime-7c865cce90132439/13aa8f0/lambda/src/lib.rs:203:29
  67: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /home/gangliao/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/future/mod.rs:80:19
  68: lambda::run::{{closure}}
             at /home/gangliao/.cargo/git/checkouts/aws-lambda-rust-runtime-7c865cce90132439/13aa8f0/lambda/src/lib.rs:158:5
  69: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /home/gangliao/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/future/mod.rs:80:19
  70: bootstrap::main::{{closure}}
             at /home/gangliao/ServerlessCQ/src/lambda.rs:17:9
  71: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /home/gangliao/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/future/mod.rs:80:19
  72: tokio::park::thread::CachedParkThread::block_on::{{closure}}
             at /home/gangliao/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.3.2/src/park/thread.rs:263:54
  73: tokio::coop::with_budget::{{closure}}
             at /home/gangliao/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.3.2/src/coop.rs:121:9
  74: std::thread::local::LocalKey<T>::try_with
             at /home/gangliao/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/thread/local.rs:272:16
  75: std::thread::local::LocalKey<T>::with
             at /home/gangliao/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/thread/local.rs:248:9
  76: tokio::coop::with_budget
             at /home/gangliao/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.3.2/src/coop.rs:114:5
  77: tokio::coop::budget
             at /home/gangliao/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.3.2/src/coop.rs:98:5
  78: tokio::park::thread::CachedParkThread::block_on
             at /home/gangliao/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.3.2/src/park/thread.rs:263:31
  79: tokio::runtime::enter::Enter::block_on
             at /home/gangliao/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.3.2/src/runtime/enter.rs:151:13
  80: tokio::runtime::thread_pool::ThreadPool::block_on
             at /home/gangliao/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.3.2/src/runtime/thread_pool/mod.rs:80:9
  81: tokio::runtime::Runtime::block_on
             at /home/gangliao/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.3.2/src/runtime/mod.rs:442:43
  82: bootstrap::main
             at /home/gangliao/ServerlessCQ/src/lambda.rs:16:5
  83: core::ops::function::FnOnce::call_once
             at /home/gangliao/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ops/function.rs:227:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
END RequestId: 7f74f64d-bc39-418c-9e77-c77dd9a47805
REPORT RequestId: 7f74f64d-bc39-418c-9e77-c77dd9a47805	Duration: 610.64 ms	Billed Duration: 700 ms	Memory Size: 128 MB	Max Memory Used: 18 MB	
RequestId: 7f74f64d-bc39-418c-9e77-c77dd9a47805 Error: Runtime exited with error: exit status 101
Runtime.ExitError
```

**Comment by rimutaka** [comment]
I noticed you use `tokio-0.3.2`. The code above should work with `tokio-0.2.*`.

I've just run into a similar problem in a unrelated project after upgrading tokio to the latest. No idea what's causing it.

**Comment by davidbarsky** [comment]
This is blocked on Hyper getting support for Tokio 0.3: https://github.com/hyperium/hyper/issues/2302. You can work around using Tokio 0.2 or use Tokio 0.3 with [`tokio-compat-02`](https://docs.rs/tokio-compat-02/0.1.2/tokio_compat_02/).

**Comment by gangliao** [comment]
@davidbarsky  @rimutaka Thanks. It works now.

**Comment by rimutaka** [comment]
Thanks @davidbarsky ! I was just about to start looking into the cause.

Can you re-open this issue so it's visible until hyperium/hyper#2302 is resolved? There will be a few more people running into this problem.

**Comment by danjenson** [comment]
I'm still getting a segmentation fault using tokio-compat-02:

`Cargo.toml`:
```toml
[package]
name = "req"
version = "0.1.0"
authors = ["X"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lambda_http = { version = "0.2.0-beta.1", git = "https://github.com/awslabs/aws-lambda-rust-runtime" }
tokio = { version = "0.3.4", features = ["full"] }
tokio-compat-02 = "0.1.2"
reqwest = { version = "0.10.9", features = ["json"] }
```

```rust
use lambda_http::{
    handler,
    lambda::{self, Context},
    IntoResponse, Request,
};
// NOTE:
// when tokio-0.2 compatibility is enabled, you get a segmentation fault
// when tokio-0.2 compatibility is not enabled, 'main' panics because 'there is
// no reactor running, must be called from the context of Tokio runtime'
// use tokio_compat_02::FutureExt;

pub type Error = Box<dyn std::error::Error + Send + Sync + 'static>;

#[tokio::main]
async fn main() -> Result<(), Error> {
    lambda::run(handler(func)).await?;
    // NOTE: [tokio-0.2 compat] - this doesn't help
    // lambda::run(handler(func)).compat().await?;
    Ok(())
}

async fn func(_: Request, _: Context) -> Result<impl IntoResponse, Error> {
    let _res = reqwest::get("https://www.google.com").await?;
    Ok("success")
}
```

`deploy.sh`:
```bash
PKG_CONFIG_ALLOW_CROSS=1 cargo build --release --target x86_64-unknown-linux-musl
cp target/x86_64-unknown-linux-musl/release/req target/x86_64-unknown-linux-musl/release/bootstrap
zip -j target/x86_64-unknown-linux-musl/release/bootstrap.zip target/x86_64-unknown-linux-musl/release/bootstrap
# aws lambda create-function \
#   --function-name reqwest-test \
#   --handler doesnt.matter \
#   --zip-file fileb://target/x86_64-unknown-linux-musl/release/bootstrap.zip \
#   --runtime provided \
#   --role [REMOVED] \
#   --environment Variables={RUST_BACKTRACE=1} \
#   --tracing-config Mode=Active
aws lambda update-function-code \
  --function-name reqwest-test \
  --zip-file fileb://target/x86_64-unknown-linux-musl/release/bootstrap.zip
```

**Comment by bahildebrand** [comment]
With #276 being closed I think this issue can be closed. All Tokio ecosystem crates have been pulled up so these compatibility issues should no longer be present.
