### ISSUE TITLE
Exit Status 101 running lambda-http hello.rs example

### ISSUE THREAD

**Issue by danjenson** [awslabs/aws-lambda-rust-runtime#268]
I've been trying to run the [example](https://github.com/awslabs/aws-lambda-rust-runtime/blob/master/lambda-http/examples/hello-http.rs), but get the following output:

```
START RequestId: 1f45b93a-b8ca-4861-ae32-b833987d2f3a Version: $LATEST
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error("data did not match any variant of untagged enum LambdaRequest", line: 0, column: 0)', src/bin/lambda.rs:8:1
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/libunwind.rs:86
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:78
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:59
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1076
   5: std::io::Write::write_fmt
             at src/libstd/io/mod.rs:1537
   6: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:62
   7: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:49
   8: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:198
   9: std::panicking::default_hook
             at src/libstd/panicking.rs:217
  10: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:526
  11: rust_begin_unwind
             at src/libstd/panicking.rs:437
  12: core::panicking::panic_fmt
             at src/libcore/panicking.rs:85
  13: core::option::expect_none_failed
             at src/libcore/option.rs:1269
  14: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  15: tokio::runtime::enter::Enter::block_on
  16: tokio::runtime::thread_pool::ThreadPool::block_on
  17: tokio::runtime::context::enter
  18: lambda::main
  19: std::rt::lang_start::{{closure}}
  20: std::rt::lang_start_internal::{{closure}}
             at src/libstd/rt.rs:52
  21: std::panicking::try::do_call
             at src/libstd/panicking.rs:348
  22: std::panicking::try
             at src/libstd/panicking.rs:325
  23: std::panic::catch_unwind
             at src/libstd/panic.rs:394
  24: std::rt::lang_start_internal
             at src/libstd/rt.rs:51
  25: main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
END RequestId: 1f45b93a-b8ca-4861-ae32-b833987d2f3a
REPORT RequestId: 1f45b93a-b8ca-4861-ae32-b833987d2f3a	Duration: 1174.83 ms	Billed Duration: 1200 ms	Memory Size: 128 MB	Max Memory Used: 31 MB	
XRAY TraceId: 1-5fbc4ea8-11c352de0d301a784d62f2e8	SegmentId: 56b495ef1aac940b	Sampled: true	
RequestId: 1f45b93a-b8ca-4861-ae32-b833987d2f3a Error: Runtime exited with error: exit status 101
Runtime.ExitError
```

Here is my `Cargo.toml`:
```{toml}
[package]
name = "example"
version = "0.1.0"
authors = ["Apple Banana"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lambda_http = { version = "0.2.0-beta.1" , git = "https://github.com/awslabs/aws-lambda-rust-runtime" }
tokio = { version = "0.2", features = ["macros"] }
```
And `main.rs`:
```{rust}
use lambda_http::{
    lambda::{lambda, Context},
    IntoResponse, Request,
};

type Error = Box<dyn std::error::Error + Send + Sync + 'static>;

#[lambda(http)]
#[tokio::main]
async fn main(_: Request, _: Context) -> Result<impl IntoResponse, Error> {
    Ok("👋 world")
}
```
And my deploy script:
```{bash}
set -x
rustup target add x86_64-unknown-linux-musl
cargo build --release --target x86_64-unknown-linux-musl
cp target/x86_64-unknown-linux-musl/release/example target/x86_64-unknown-linux-musl/release/bootstrap
zip -j target/x86_64-unknown-linux-musl/release/bootstrap.zip target/x86_64-unknown-linux-musl/release/bootstrap
# aws lambda create-function \
#   --function-name "aws-lambda-test" \
#   --handler "doesnt.matter" \
#   --zip-file fileb://target/x86_64-unknown-linux-musl/release/bootstrap.zip \
#   --runtime "provided" \
#   --role "[REMOVED]" \
#   --environment "Variables={RUST_BACKTRACE=1}" \
#   --tracing-config "Mode=Active"
aws lambda update-function-code \
  --function-name motoko-graphql-dev \
  --zip-file fileb://target/x86_64-unknown-linux-musl/release/bootstrap.zip
```

**Comment by softprops** [comment]
How are you invoking your lambda? These interfaces in particular assume a trigger event payload of a certain shape.

I see a hint that might be the case in your backtrace.

**Comment by danjenson** [comment]
Regardless of whether I invoke it through the API gateway or pass and empty json to the test event, I get the same result.

**Comment by brainstorm** [comment]
@danjenson What does your test event (.json format) look like? I believe I've been bitten by this before.

**Comment by danjenson** [comment]
either blank or {}

**Comment by brainstorm** [comment]
If your project is setup with SAM, you might want to read/test/compare with my own example: https://github.com/brainstorm/s3-rust-htslib-bam... I hope that does not confuse you further, but at least I know mine works and perhaps you can find the culprit by proxy ;)

**Comment by danjenson** [comment]
When using the most recent version of tokio = "0.3.4", the error changes to

```
thread 'main' panicked at 'there is no reactor running, must be called from the context of Tokio runtime', /home/danj/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.23/src/io/driver/mod.rs:204:14
```

**Comment by brainstorm** [comment]
@danjenson Don't touch Tokio versions, I've been there myself already:

https://github.com/brainstorm/s3-rust-htslib-bam/commit/db0653e5032784bd562dbed4df1517ef90262bce#commitcomment-40587195

It really looks like your event should be something else than blank or `{}`.

**Comment by danjenson** [comment]
So with API gateway you can't even set the body on a GET request.

**Comment by brainstorm** [comment]
Test the lambda by itself first, ignore API gateway.

**Comment by danjenson** [comment]
Well, my thought is that APIGateway is one of the 3 LambdaRequest types defined here: https://github.com/awslabs/aws-lambda-rust-runtime/blob/ed40f5a7b7e8f09a679f7b6b6334e5e3ed86b1de/lambda-http/src/request.rs, and a GET request should be the simplest version of this. It seems more error prone to try to manually recreate one of these enum types.

**Comment by softprops** [comment]
We have some samples used for testing [here](https://github.com/awslabs/aws-lambda-rust-runtime/tree/ed40f5a7b7e8f09a679f7b6b6334e5e3ed86b1de/lambda-http/tests/data) based on actual requests.

We we can come up with a new test case for an actual requests payload that's failing that would be the best way to identify the issue.

Atm we don't really support requests that may be missing certain fields or don't fit these shapes.

**Comment by danjenson** [comment]
So why would a GET request directly from API Gateway fail? Shouldn't it have all the required fields?

**Comment by danjenson** [comment]
So _one_ part of the problem seems to be that Proxy has to be checked under Integration Request in the API Gateway. If it is not checked, you will get an error. The second part of the problem seems to be with redirections, i.e. a call to mydomain.com/graphql fails with Exit Status 101, but a direct call to  api.mydomain.com/graphql succeeds, when the former should simply be redirecting to the latter.

**Comment by danjenson** [comment]
Closing since this seems to be solved by turning on the Proxy in the API Gateway.
