### ISSUE TITLE
Invoke Doesn't Work?

### ISSUE THREAD

**Issue by JimLynchCodes** [awslabs/aws-lambda-rust-runtime#417]
Hi!

I followed the guide here and am trying to run the "invoke" command to invoke the function locally, but it gives me a strange error...

`npx serverless invoke -f hello` gives me this error:

```
Warning: Invalid configuration encountered
  at 'provider.runtime': must be equal to one of the allowed values [dotnetcore3.1, go1.x, java11, java8, java8.al2, nodejs12.x, nodejs14.x, provided, provided.al2, python3.6, python3.7, python3.8, python3.9, ruby2.7]

Learn more about configuration validation here: http://slss.io/configuration-validation
{
    "errorMessage": "RequestId: eb0cc110-3a94-462e-a49d-328bd71e46c7 Error: Runtime exited with error: exit status 1",
    "errorType": "Runtime.ExitError"
}
Environment: darwin, node 16.13.2, framework 3.2.1 (local), plugin 6.0.0, SDK 4.3.1
Credentials: Local, "default" profile
Docs:        docs.serverless.com
Support:     forum.serverless.com
Bugs:        github.com/serverless/serverless/issues

Error:
Invoked function failed

1 deprecation found: run 'serverless doctor' for more details
``` 

when I run `serverless doctor` it just says this:
```
Running "serverless" from node_modules
1 deprecation triggered in the last command:

Starting with the next major, Serverless will throw on configuration errors by default. Adapt to this behavior now by adding "configValidationMode: error" to the service configuration
More info: https://serverless.com/framework/docs/deprecations/#CONFIG_VALIDATION_MODE_DEFAULT_V3

```

**Comment by nmoutschen** [comment]
Hey @JimLynchCodes!

Could you check if you have the [serverless-rust](https://github.com/softprops/serverless-rust) installed and configured in your `serverless.yml`?

If you're using one of the examples that uses `rust` as the runtime, you'll need to use that plugin. Otherwise, it'll throw an error as `rust` is not a valid runtime.

**Comment by JimLynchCodes** [comment]
Thanks @nmoutschen !

I tried installing the plugin with: `serverless plugin install -n serverless-rust`

Now, though when I try to invoke local I get this error:
```
Running "serverless" from node_modules
Serverless: Deprecation Notice: bin/serverless is deprecated, use bin/serverless.js instead
            More Info: https://www.serverless.com/framework/docs/deprecations/#BIN_SERVERLESS
Serverless: Building Rust hello func...
Serverless: Running containerized build
   Compiling indexmap v1.8.0
   Compiling socket2 v0.4.4
   Compiling time v0.1.43
   Compiling openssl v0.10.38
   Compiling openssl-sys v0.9.72
   Compiling native-tls v0.2.8
   Compiling syn v1.0.86
   Compiling mio v0.6.22
error[E0658]: use of unstable library feature 'vec_drain_as_slice': recently added
    --> /root/.cargo/registry/src/github.com-1ecc6299db9ec823/indexmap-1.8.0/src/map.rs:1182:30
     |
1182 |         let iter = self.iter.as_slice().iter().map(Bucket::refs);
     |                              ^^^^^^^^
     |
     = note: see issue #58957 <https://github.com/rust-lang/rust/issues/58957> for more information

error[E0658]: `match` is not allowed in a `const fn`
   --> /root/.cargo/registry/src/github.com-1ecc6299db9ec823/socket2-0.4.4/src/lib.rs:165:9
    |
165 | /         match address {
166 | |             SocketAddr::V4(_) => Domain::IPV4,
167 | |             SocketAddr::V6(_) => Domain::IPV6,
168 | |         }
    | |_________^
    |
    = note: see issue #49146 <https://github.com/rust-lang/rust/issues/49146> for more information

error[E0658]: use of unstable library feature 'vec_drain_as_slice': recently added
   --> /root/.cargo/registry/src/github.com-1ecc6299db9ec823/indexmap-1.8.0/src/set.rs:842:30
    |
842 |         let iter = self.iter.as_slice().iter().map(Bucket::key_ref);
    |                              ^^^^^^^^
    |
    = note: see issue #58957 <https://github.com/rust-lang/rust/issues/58957> for more information

error: aborting due to 2 previous errors

For more information about this error, try `rustc --explain E0658`.
error: could not compile `indexmap`.

To learn more, run the command again with --verbose.
warning: build failed, waiting for other jobs to finish...
error[E0658]: the `#[track_caller]` attribute is an experimental feature
  --> /root/.cargo/registry/src/github.com-1ecc6299db9ec823/openssl-sys-0.9.72/src/crypto.rs:17:1
   |
17 | #[track_caller]
   | ^^^^^^^^^^^^^^^
   |
   = note: see issue #47809 <https://github.com/rust-lang/rust/issues/47809> for more information

error: aborting due to previous error

For more information about this error, try `rustc --explain E0658`.
error: could not compile `socket2`.

To learn more, run the command again with --verbose.
warning: build failed, waiting for other jobs to finish...
error: aborting due to previous error

For more information about this error, try `rustc --explain E0658`.
error: could not compile `openssl-sys`.

To learn more, run the command again with --verbose.
warning: build failed, waiting for other jobs to finish...
error: build failed
Serverless: Rust build encountered an error: undefined 1.
 
  Error --------------------------------------------------
 
  Error: 
      at /Users/jim/Git-Projects/joke-fetcher-crab-lamb/node_modules/serverless-rust/index.js:289:15
      at Array.forEach (<anonymous>)
      at RustPlugin.build (/Users/jim/Git-Projects/joke-fetcher-crab-lamb/node_modules/serverless-rust/index.js:269:22)
      at /Users/jim/Git-Projects/joke-fetcher-crab-lamb/node_modules/serverless/lib/classes/PluginManager.js:476:55
      at tryCatcher (/Users/jim/Git-Projects/joke-fetcher-crab-lamb/node_modules/bluebird/js/release/util.js:16:23)
      at Object.gotValue (/Users/jim/Git-Projects/joke-fetcher-crab-lamb/node_modules/bluebird/js/release/reduce.js:168:18)
      at Object.gotAccum (/Users/jim/Git-Projects/joke-fetcher-crab-lamb/node_modules/bluebird/js/release/reduce.js:155:25)
      at Object.tryCatcher (/Users/jim/Git-Projects/joke-fetcher-crab-lamb/node_modules/bluebird/js/release/util.js:16:23)
      at Promise._settlePromiseFromHandler (/Users/jim/Git-Projects/joke-fetcher-crab-lamb/node_modules/bluebird/js/release/promise.js:547:31)
      at Promise._settlePromise (/Users/jim/Git-Projects/joke-fetcher-crab-lamb/node_modules/bluebird/js/release/promise.js:604:18)
      at Promise._settlePromise0 (/Users/jim/Git-Projects/joke-fetcher-crab-lamb/node_modules/bluebird/js/release/promise.js:649:10)
      at Promise._settlePromises (/Users/jim/Git-Projects/joke-fetcher-crab-lamb/node_modules/bluebird/js/release/promise.js:729:18)
      at _drainQueueStep (/Users/jim/Git-Projects/joke-fetcher-crab-lamb/node_modules/bluebird/js/release/async.js:93:12)
      at _drainQueue (/Users/jim/Git-Projects/joke-fetcher-crab-lamb/node_modules/bluebird/js/release/async.js:86:9)
      at Async._drainQueues (/Users/jim/Git-Projects/joke-fetcher-crab-lamb/node_modules/bluebird/js/release/async.js:102:5)
      at Immediate.Async.drainQueues [as _onImmediate] (/Users/jim/Git-Projects/joke-fetcher-crab-lamb/node_modules/bluebird/js/release/async.js:15:14)
      at processImmediate (node:internal/timers:464:21)
 
     For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com
 
  Your Environment Information ---------------------------
     Operating System:          darwin
     Node Version:              16.13.2
     Framework Version:         1.74.1
     Plugin Version:            3.6.15
     SDK Version:               2.3.1
     Components Version:        2.31.10
```

**Comment by nmoutschen** [comment]
Hey @JimLynchCodes!

Could you check which version of Rust you are using by running `rustc --version`?

The latest version of Rust is 1.58.1, and the minimum supported Rust version (MSRV) for the Lambda runtime is 1.54.0 at the moment. One of the features mentioned (track_caller) is stable since Rust 1.46.0, so I suppose you might have a fairly old version of Rust at the moment, which doesn't support some of these features.

**Comment by JimLynchCodes** [comment]
Is there some extra OpenSSL configuration needed to make this work? 🤔

**Comment by nmoutschen** [comment]
This sounds like an issue related to OpenSSL for `x86_64-unknown-linux-musl` not being installed on your host system.

From the `openssl-sys` crate, it looks like you're trying to use the OS-specific implementation of TLS (OpenSSL for Linux). If the specific library is not present, you'll get that exception.

The easiest way to solve this issue is to switch to a full Rust implementation (`rustls`). You might have one or multiple crates pulling `openssl-sys`. To discover that, you can run the following command, and search for dependencies to openssl-sys:

```bash
cargo tree
```

Different crates will have feature flags for rustls or native-tls implementations, so you'd need to refer to the documentation of those crates.

---

As a side note, are you using the sample implementations from the Serverless framework section? I noticed that the linked GitHub repositories haven't been updated in 2+ years now, so they might be using obsolete versions of crates.

**Comment by nmoutschen** [comment]
Hey @JimLynchCodes ! Since there hasn't been any activity for over two weeks and there's no real issue with the runtime, I'll go ahead and close this ticket.

If you're still facing issues with building Lambda functions in Rust, feel free to start a [new discussion](https://github.com/awslabs/aws-lambda-rust-runtime/discussions) and I'll be happy to look at it.
