### ISSUE TITLE
AWS Lambda fails to deserialize query parameters involving encoded JSON blobs

### ISSUE THREAD

**Issue by seanpianka** [awslabs/aws-lambda-rust-runtime#489]
Deployed to AWS Lambda using Rust 1.60 on Alpine 3.15, and using version 0.5.1 of the runtime as specified in the simple-http example.

The following stacktrace is thrown when deserializing the URI from an upstream API gateway request `http::Error(InvalidUri(InvalidUriChar))`. The request's URI contains an encoded `"` in the value of a query parameter, e.g. `?mapping=%7D%22foo%22`, based on the default behavior for axios (a JS HTTP client package) which percent-encodes all query parameter values sent in GET requests.

```
  | 2022-06-14T19:54:45.906-04:00 | thread 'main' panicked at 'failed to build request: http::Error(InvalidUri(InvalidUriChar))', /builds/my-cool-project/api/.cargo/registry/src/github.com-1ecc6299db9ec823/lambda_http-0.5.1/src/request.rs:170:10
  | 2022-06-14T19:54:45.906-04:00 | stack backtrace:
  | 2022-06-14T19:54:45.906-04:00 | 0: rust_begin_unwind
  | 2022-06-14T19:54:45.906-04:00 | at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panicking.rs:584:5
  | 2022-06-14T19:54:45.906-04:00 | 1: core::panicking::panic_fmt
  | 2022-06-14T19:54:45.906-04:00 | at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/panicking.rs:143:14
  | 2022-06-14T19:54:45.906-04:00 | 2: core::result::unwrap_failed
  | 2022-06-14T19:54:45.906-04:00 | at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/result.rs:1749:5
  | 2022-06-14T19:54:45.906-04:00 | 3: lambda_http::request::<impl core::convert::From<lambda_http::request::LambdaRequest> for http::request::Request<aws_lambda_events::encodings::Body>>::from
  | 2022-06-14T19:54:45.906-04:00 | 4: lambda_runtime::Runtime<C>::run::{{closure}}
  | 2022-06-14T19:54:45.906-04:00 | 5: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  | 2022-06-14T19:54:45.906-04:00 | 6: my_cool_project::main
  | 2022-06-14T19:54:45.906-04:00 | note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
  | 2022-06-14T19:54:45.907-04:00 | {"v":0,"name":"my-cool-project","msg":"Any { .. }","level":50,"hostname":"x.x.x.x","pid":8,"time":"2022-06-14T23:54:45.9070253Z","target":"lambda_runtime","line":157,"file":"/builds/my-cool-project/.cargo/registry/src/github.com-1ecc6299db9ec823/lambda_runtime-0.5.1/src/lib.rs"}
```

Here are some query parameter values that I've found to throw this stacktrace:
* `%22`
* `%7D%22%7B`
* `%7D%22%22%7B`
* `%7B%22foo%22%7D`

Here's some inputs that did not panic:
* `%7D%7B`
* `%7D""%7B`

**Comment by seanpianka** [comment]
Yep, that resolved it, thanks!
