### ISSUE TITLE
Error during dispatch: error trying to connect: invalid peer certificate contents: invalid peer certificate: UnknownIssuer

### ISSUE THREAD

**Issue by ferologics** [awslabs/aws-lambda-rust-runtime#499]
### Description
Encountered the following error when calling `IotDataClient.publish`:

```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: HttpDispatch(HttpDispatchError { message: "Error during dispatch: error trying to connect: invalid peer certificate contents: invalid peer certificate: UnknownIssuer" })', src/main.rs:62:13
```

### Reproduction steps
1. create a lambda with arm64 (or x86_64, both have the same issue)
2. package attached lambda with `cargo lambda build --release --arm64 --output-format zip`
3. set up the following IoT rule trigger: `SELECT * FROM "rust_lambda_mqtt"`
4. send a test event json `{ "command": "test" }` to `rust_lambda_mqtt` topic to trigger the lambda
5. observe the above reported error

### Implementation

<details>
<summary>Cargo.toml</summary>

```
[package]
name = "lambda"
version = "0.1.0"
edition = "2021"

# Use cargo-edit(https://github.com/killercup/cargo-edit#installation)
# to manage dependencies.
# Running `cargo add DEPENDENCY_NAME` will
# add the latest version of a dependency to the list,
# and it will keep the alphabetic ordering for you.

[dependencies]
bincode = "1.3.3"
bytes = "1.1.0"
lambda_runtime = "0.5.1"
serde = "1.0.136"
tokio = { version = "1", features = ["macros"] }
tracing = { version = "0.1", features = ["log"] }
tracing-subscriber = { version = "0.3", default-features = false, features = ["fmt"] }
rusoto_core = { version = "0.48.0", default_features = false, features = ["rustls"] }
rusoto_iot_data = { version = "0.48.0", default_features = false, features = ["rustls"] }
```

</details>

<details>
<summary>main.rs</summary>

```rust
use lambda_runtime::{run, service_fn, Error, LambdaEvent};
use serde::{Deserialize, Serialize};
use rusoto_core::Region;
use rusoto_iot_data::{IotData, IotDataClient, PublishRequest};
use bytes::Bytes;

/// This is a made-up example. Requests come into the runtime as unicode
/// strings in json format, which can map to any structure that implements `serde::Deserialize`
/// The runtime pays no attention to the contents of the request payload.
#[derive(Deserialize)]
struct Request {
    command: String,
}

/// This is a made-up example of what a response structure may look like.
/// There is no restriction on what it can be. The runtime requires responses
/// to be serialized into json. The runtime pays no attention
/// to the contents of the response payload.
#[derive(Serialize)]
struct Response {
    msg: String
}

/// This is the main body for the function.
/// Write your code inside it.
/// There are some code example in the following URLs:
/// - https://github.com/awslabs/aws-lambda-rust-runtime/tree/main/lambda-runtime/examples
/// - https://github.com/aws-samples/serverless-rust-demo/
async fn function_handler(event: LambdaEvent<Request>) -> Result<Response, Error> {
    // Extract some useful info from the request
    let command = event.payload.command;
    let reversed_cmd = command.chars().rev().collect::<String>();
    
    // Prepare the response
    let resp = Response { msg: reversed_cmd };
    let payload = Some(Bytes::from(bincode::serialize(&resp).unwrap()));
    
    // Publish response to topic
    let iot_client = IotDataClient::new(Region::UsWest2);
    iot_client.publish(
        PublishRequest {
            topic: String::from("rust_lambda_mqtt"),
            payload: payload,
            qos: None,
        }
    ).await.unwrap();
    
    // Return `Response` (it will be serialized to JSON automatically by the runtime)
    Ok(resp)
}

#[tokio::main]
async fn main() -> Result<(), Error> {
    tracing_subscriber::fmt()
        .with_max_level(tracing::Level::INFO)
        // disabling time is handy because CloudWatch will add the ingestion time.
        .without_time()
        .init();

    run(service_fn(function_handler)).await
}
```

</details>

<details>
<summary>IAM role policy used</summary>

```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": [
                "iot:Publish"
            ],
            "Resource": [
                "*"
            ]
        }
    ]
}
```

</details>

### Conclusion
Custom runtime v2 with rust doesn't seem to be working with the base container. Might just be something with the path of the SSL certs that causes this. The lambda works fine when it's ran locally, the problem starts occurring once it's deployed. Running the lambda on x86_64 arch yields the same error.

<details>
<summary>working local lambda test screenshot</summary>

![image](https://user-images.githubusercontent.com/5576161/177771422-2f281632-4b60-49b4-b050-a9e146f79014.png)

</details>

### Environment
- macOS 12.4 (21F79)
- MacBook Pro (16-inch, 2021)
- Apple M1 Pro
- Custom runtime: Amazon Linux 2 (arm64 & x86_64)
- lambda runtime `0.5.1`

### Resources
- the source for [rust-lambda.zip](https://github.com/awslabs/aws-lambda-rust-runtime/files/9063541/rust-lambda.zip)
- the deployed [arm64 bootstrap.zip](https://github.com/awslabs/aws-lambda-rust-runtime/files/9063558/bootstrap.zip) and [x86_64 bootstrap.zip](https://github.com/awslabs/aws-lambda-rust-runtime/files/9063546/bootstrap.zip)

<details>
<summary>full debug error</summary>

```
START RequestId: 5af5960f-60de-42c1-98fd-a25316268468 Version: $LATEST
[src/main.rs:75] "tomraff main" = "tomraff main"
DEBUG hyper::client::connect::http: connecting to 127.0.0.1:9001
DEBUG hyper::client::connect::http: connected to 127.0.0.1:9001
DEBUG hyper::proto::h1::io: flushed 109 bytes
DEBUG hyper::proto::h1::io: parsed 7 headers
DEBUG hyper::proto::h1::conn: incoming body is content-length (18 bytes)
DEBUG hyper::proto::h1::conn: incoming body completed
DEBUG hyper::client::pool: pooling idle connection for ("http", 127.0.0.1:9001)
ERROR lambda: tomraff first
[src/main.rs:52] "creating ito client" = "creating ito client"
DEBUG hyper::client::connect::dns: resolving host="data.iot.us-west-2.amazonaws.com"
DEBUG hyper::client::connect::http: connecting to 52.35.93.134:443
DEBUG hyper::client::connect::http: connected to 52.35.93.134:443
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: HttpDispatch(HttpDispatchError { message: "Error during dispatch: error trying to connect: invalid peer certificate contents: invalid peer certificate: UnknownIssuer" })', src/main.rs:62:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
END RequestId: 5af5960f-60de-42c1-98fd-a25316268468
REPORT RequestId: 5af5960f-60de-42c1-98fd-a25316268468	Duration: 882.35 ms	Billed Duration: 947 ms	Memory Size: 128 MB	Max Memory Used: 26 MB	Init Duration: 64.35 ms	
RequestId: 5af5960f-60de-42c1-98fd-a25316268468 Error: Runtime exited with error: exit status 101
Runtime.ExitError
```

</details>

### Similar issues found online
- https://github.com/rusoto/rusoto/issues/1862
- https://github.com/awslabs/aws-sdk-rust/issues/468
- https://stackoverflow.com/questions/62644469/hyper-error-invalid-certificate-unknownissuer

**Comment by ferologics** [comment]
Workaround is to use the provided Amazon Linux 1 runtime (instead of custom) and compile the lambda with `cargo lambda build --release --target x86_64-unknown-linux-gnu.2.17 --output-format zip` which produces a working [bootstrap.zip](https://github.com/awslabs/aws-lambda-rust-runtime/files/9063699/bootstrap.zip).

<details>
<summary>screenshot of successful test using Amazon Linux 1 runtime</summary>

<img width="1217" alt="image" src="https://user-images.githubusercontent.com/5576161/177777432-4a39fd5b-fcf6-4090-9776-570bbd9a0ccf.png">

</details>
