### ISSUE TITLE
Runtime error when reading Kinesis records

### ISSUE THREAD

**Issue by premjg** [awslabs/aws-lambda-rust-runtime#66]
I tried it out by connecting to a Kinesis stream and encountered the following error:
(Interestingly when I try the Lambda UI Console test cases (using the provided Kinesis template test cases), I don't see any errors.)

```
START RequestId: 7ea355dc-77ee-4cbc-aa9e-f18d6264fc5a Version: $LATEST
2018-12-29 10:33:36 ERROR [lambda_runtime::runtime] Could not parse event to type: invalid type: floating point `1546079388.123`, expected i64 at line 1 column 10108
2018-12-29 10:33:37 ERROR [lambda_runtime::runtime] Could not parse event to type: invalid type: floating point `1546079388.123`, expected i64 at line 1 column 10108
2018-12-29 10:33:37 ERROR [lambda_runtime::runtime] Could not parse event to type: invalid type: floating point `1546079388.123`, expected i64 at line 1 column 10108
2018-12-29 10:33:37 ERROR [lambda_runtime::runtime] Could not parse event to type: invalid type: floating point `1546079388.123`, expected i64 at line 1 column 10108
2018-12-29 10:33:37 ERROR [lambda_runtime::runtime] Unrecoverable error while fetching next event: JSON error
thread 'main' panicked at 'Could not retrieve next event', /root/.cargo/registry/src/github.com-1ecc6299db9ec823/lambda_runtime-0.1.0/src/runtime.rs:267:17
stack backtrace:
0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
at src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
1: std::sys_common::backtrace::_print
at src/libstd/sys_common/backtrace.rs:80
2: std::panicking::default_hook::{{closure}}
at src/libstd/sys_common/backtrace.rs:68
at src/libstd/panicking.rs:210
3: std::panicking::default_hook
at src/libstd/panicking.rs:225
4: std::panicking::rust_panic_with_hook
at src/libstd/panicking.rs:488
5: std::panicking::begin_panic
6: <lambda_runtime::runtime::Runtime<E, O>>::get_next_event
7: <lambda_runtime::runtime::Runtime<E, O>>::get_next_event
8: <lambda_runtime::runtime::Runtime<E, O>>::get_next_event
9: <lambda_runtime::runtime::Runtime<E, O>>::get_next_event
10: <lambda_runtime::runtime::Runtime<E, O>>::get_next_event
11: lambda_runtime::runtime::start
12: bootstrap::main
13: std::rt::lang_start::{{closure}}
14: std::panicking::try::do_call
at src/libstd/rt.rs:59
at src/libstd/panicking.rs:307
15: __rust_maybe_catch_panic
at src/libpanic_unwind/lib.rs:102
16: std::rt::lang_start_internal
at src/libstd/panicking.rs:286
at src/libstd/panic.rs:398
at src/libstd/rt.rs:58
17: main
END RequestId: 7ea355dc-77ee-4cbc-aa9e-f18d6264fc5a
```

After scanning through the library code, I think it has an issue parsing the `"ApproximateArrivalTimestamp` in Kinesis payload which looks like a float.

**Comment by premjg** [comment]
I can confirm that changing the test case to the following does yield the same error.
(I manually changed the `approximateArrivalTimestamp` from an `int` to a `float`.)

```
{
  "Records": [
    {
      "kinesis": {
        "partitionKey": "partitionKey-03",
        "kinesisSchemaVersion": "1.0",
        "data": "SGVsbG8sIHRoaXMgaXMgYSB0ZXN0IDEyMy4=",
        "sequenceNumber": "49545115243490985018280067714973144582180062593244200961",
        "approximateArrivalTimestamp": 1428537600.123
      },
      "eventSource": "aws:kinesis",
      "eventID": "shardId-000000000000:49545115243490985018280067714973144582180062593244200961",
      "invokeIdentityArn": "arn:aws:iam::EXAMPLE",
      "eventVersion": "1.0",
      "eventName": "aws:kinesis:record",
      "eventSourceARN": "arn:aws:kinesis:EXAMPLE",
      "awsRegion": "ap-southeast-2"
    }
  ]
}
```

**Comment by davidbarsky** [comment]
Thanks for reporting this, and I'm sorry that you ran into this!

It's entirely possible that I'm missing something here, but can you share your event definition? In our event fetching code, we're [generic over the event type](https://github.com/awslabs/aws-lambda-rust-runtime/blob/master/lambda-runtime/src/runtime.rs#L276), so I don't expect anything _we're_ doing to be the cause of the issue—if it's us to blame, I'm sorry.

As for: 

> I can confirm that changing the test case to the following does yield the same error. (I manually changed the `approximateArrivalTimestamp` from an `int` to a `float`.)

As I mentioned earlier, I suspect that your event definition is specifying an `i64` when it should be specifying an `f64`. Serde is _very_ strict about parsing values, so it will not perform an automatic conversion from a float to an integer.

**Comment by premjg** [comment]
🤦‍♂️ 

It was indeed my `Event` struct. Sorry about that.
Once I fixed it based on your suggestion, everything seems to work fine.

Thanks for the prompt response and help.
(Closing the issue)
